import { Book, Review } from "./types";

export const SEED_BOOKS: Book[] = [
  {
    id: "g1",
    title: "Монгол ардын үлгэрүүд",
    author: "Эмхэтгэсэн: Д. Цэрэндагва",
    category: "children",
    condition: "like_new",
    description: "Бага ангийн сурагчдад хамгийн тохиромжтой, зурагтай үлгэрүүд.",
    source: "official",
    status: "active",
    priceCash: 5000,
    ownerName: "Level Up Stock",
    images: [],
    avgRating: 4.8,
    reviewCount: 24,
    createdAt: "2026-09-10",
  },
  {
    id: "g2",
    title: "Харри Поттер ба Философийн чулуу",
    author: "Ж.К. Роулинг",
    category: "fiction",
    condition: "good",
    description: "Монгол орчуулга, 2 удаа уншсан, хавтас сайн.",
    source: "user",
    status: "active",
    priceCash: 5000,
    ownerName: "Анужин (10-р анги)",
    images: [],
    avgRating: 4.9,
    reviewCount: 41,
    createdAt: "2026-09-18",
  },
  {
    id: "g3",
    title: "Физик 10-р анги",
    author: "БШУЯ сурах бичиг",
    category: "textbook",
    condition: "good",
    description: "Сурах бичиг, тэмдэглэл багатай, шалгалтад бэлдэхэд сайн.",
    source: "user",
    status: "active",
    priceCash: 5000,
    ownerName: "Тэмүүлэн (11-р анги)",
    images: [],
    avgRating: 4.2,
    reviewCount: 9,
    createdAt: "2026-09-19",
  },
  {
    id: "g4",
    title: "Бяцхан ханхүү",
    author: "Антуан де Сент-Экзюпери",
    category: "fiction",
    condition: "new",
    description: "Шинэ шахам, бэлгэнд өгөхөд тохиромжтой.",
    source: "official",
    status: "active",
    priceCash: 5000,
    ownerName: "Level Up Stock",
    images: [],
    avgRating: 4.7,
    reviewCount: 33,
    createdAt: "2026-09-08",
  },
  {
    id: "g5",
    title: "Математик 9-р анги бодлогын хураамж",
    author: "Д. Оюунчимэг",
    category: "textbook",
    condition: "used",
    description: "Ашигласан ч дутуу хуудасгүй, бодлого ихтэй.",
    source: "user",
    status: "active",
    priceCash: 5000,
    ownerName: "Билгүүн (9-р анги)",
    images: [],
    avgRating: 4.0,
    reviewCount: 6,
    createdAt: "2026-09-20",
  },
  {
    id: "g6",
    title: "Дэлхийн түүх хүүхдэд",
    author: "Орчуулгын баг",
    category: "children",
    condition: "like_new",
    description: "Зурагтай, том үсэгтэй, уншихад хялбар.",
    source: "official",
    status: "active",
    priceCash: 5000,
    ownerName: "Level Up Stock",
    images: [],
    avgRating: 4.5,
    reviewCount: 12,
    createdAt: "2026-09-05",
  },
  {
    id: "g7",
    title: "Алхимич",
    author: "Пауло Коэльо",
    category: "fiction",
    condition: "good",
    description: "Оюутнуудын дуртай, урам зориг өгдөг ном.",
    source: "user",
    status: "pending",
    priceCash: 5000,
    ownerName: "Сарнай (МУИС)",
    images: [],
    avgRating: 4.6,
    reviewCount: 18,
    createdAt: "2026-09-21",
  },
  {
    id: "g8",
    title: "Англи хэлний үгсийн сан 1000",
    author: "Б. Нарангарав",
    category: "textbook",
    condition: "new",
    description: "Шинэ, EJU / IELTS-д бэлдэгчдэд тохиромжтой.",
    source: "official",
    status: "active",
    priceCash: 5000,
    ownerName: "Level Up Stock",
    images: [],
    avgRating: 4.4,
    reviewCount: 15,
    createdAt: "2026-09-12",
  },
  {
    id: "g9",
    title: "Том Сойерын адал явдал",
    author: "Марк Твен",
    category: "children",
    condition: "good",
    description: "Хүүхдийн сонгодог, орчуулга сайн.",
    source: "user",
    status: "active",
    priceCash: 5000,
    ownerName: "Хүслэн (8-р анги)",
    images: [],
    avgRating: 4.6,
    reviewCount: 11,
    createdAt: "2026-09-17",
  },
  {
    id: "g10",
    title: "1984",
    author: "Жорж Оруэлл",
    category: "fiction",
    condition: "used",
    description: "Ахлах анги, оюутанд заавал унших ном.",
    source: "user",
    status: "active",
    priceCash: 5000,
    ownerName: "Энхжин (12-р анги)",
    images: [],
    avgRating: 4.7,
    reviewCount: 27,
    createdAt: "2026-09-15",
  },
  {
    id: "g11",
    title: "Хими 11-р анги",
    author: "БШУЯ сурах бичиг",
    category: "textbook",
    condition: "like_new",
    description: "Шинэвтэр, хавтас нугалаагүй.",
    source: "user",
    status: "sold",
    priceCash: 5000,
    ownerName: "Дөлгөөн",
    images: [],
    avgRating: 4.1,
    reviewCount: 5,
    createdAt: "2026-09-02",
  },
  {
    id: "g12",
    title: "Шидэт мозайк үлгэр",
    author: "О. Сүнжидмаа",
    category: "children",
    condition: "new",
    description: "Цэцэрлэг, бага ангийн хүүхдэд зориулсан.",
    source: "official",
    status: "active",
    priceCash: 5000,
    ownerName: "Level Up Stock",
    images: [],
    avgRating: 4.3,
    reviewCount: 8,
    createdAt: "2026-09-11",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "r1",
    bookId: "g2",
    userName: "Бат-Эрдэнэ",
    rating: 5,
    text: "Орчуулга нь маш ойлгомжтой, хүү маань 2 хоногт уншиж дуусгасан.",
    createdAt: "2026-09-19",
  },
  {
    id: "r2",
    bookId: "g2",
    userName: "Мишээл",
    rating: 5,
    text: "Хавтас нь бодсоноос цэвэрхэн ирсэн. Кредитээр хямд авсан.",
    createdAt: "2026-09-20",
  },
  {
    id: "r3",
    bookId: "g4",
    userName: "Оюука",
    rating: 5,
    text: "Бэлгэнд өгсөн, маш гоё хавтастай.",
    createdAt: "2026-09-12",
  },
];
